title: Tutorial Website
description: Resources for ASTA's summer training, 2025.
theme: just-the-docs

logo: "/assets/images/thuasta.png"

url: https://orisnow420.github.io/tutorial-website/

aux_links:
  GitHub: https://github.com/OriSnow420/tutorial-website
  THUASTA: https://thuasta.org/
